# Generated by Django 2.1.7 on 2019-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_category',
            name='url',
            field=models.CharField(default='b', max_length=30),
            preserve_default=False,
        ),
    ]
