# Generated by Django 2.1.7 on 2019-04-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_event_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('lenisters', models.IntegerField(blank=True, null=True)),
                ('baratheons', models.IntegerField(blank=True, null=True)),
                ('targaryens', models.IntegerField(blank=True, null=True)),
                ('starks', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
