# Generated by Django 2.1.7 on 2019-04-16 21:27

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_egg_drop_item_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='know_your_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=events.models.get_city_path)),
            ],
        ),
        migrations.CreateModel(
            name='paheli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=events.models.get_paheli_path)),
            ],
        ),
    ]
