# Generated by Django 2.1.7 on 2019-04-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_know_your_city_paheli'),
    ]

    operations = [
        migrations.AddField(
            model_name='paheli',
            name='answer',
            field=models.CharField(default='aaa', max_length=500),
            preserve_default=False,
        ),
    ]
