# Generated by Django 2.1.7 on 2019-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2),
            preserve_default=False,
        ),
    ]
